python3 main_linear.py \
    --dataset cifar10 \
    --backbone resnet18 \
    --train_data_path ./datasets \
    --val_data_path ./datasets \
    --max_epochs 100 \
    --devices 0 \
    --accelerator gpu \
    --precision 16 \
    --optimizer sgd \
    --lr 0.3 \
    --scheduler warmup_cosine \
    --warmup_epochs 0 \
    --weight_decay 1e-5 \
    --batch_size 256 \
    --num_workers 0 \
    --pretrained_feature_extractor $1 \
    --name lp-resnet18-cifar10-linear-eval \
    --entity evrimozmermer \
    --project ssl-lp-whitepaper \
    --wandb \
    --save_checkpoint \
    --auto_resume
