python3 main_pretrain.py \
    --dataset cifar10 \
    --backbone resnet18 \
    --train_data_path ./datasets \
    --val_data_path ./datasets \
    --max_epochs 1500 \
    --devices 0 \
    --accelerator gpu \
    --precision 16 \
    --num_workers 2 \
    --optimizer lars \
    --grad_clip_lars \
    --eta_lars 0.02 \
    --exclude_bias_n_norm_lars \
    --scheduler warmup_cosine \
    --lr 0.3 \
    --weight_decay 1e-4 \
    --batch_size 128 \
    --brightness 0.4 \
    --contrast 0.4 \
    --saturation 0.2 \
    --hue 0.1 \
    --gaussian_prob 0.0 0.0 \
    --solarization_prob 0.0 0.2 \
    --crop_size 32 \
    --num_crops_per_aug 1 1 \
    --knn_eval \
    --name barlow_1 \
    --project acc-data-ai \
    --entity evrimozmermer \
    --wandb \
    --save_checkpoint \
    --auto_resume \
    --auto_resumer_max_hours 240 \
    --method barlow_twins \
    --proj_hidden_dim 512 \
    --proj_output_dim 64 \
    --scale_loss 0.1
